MODULE element_table_mod
    ! Borrowed and edited from @smillerc fortran_periodic_table

    PRIVATE
    PUBLIC :: get_element, atomic_element

    TYPE :: atomic_element 
        CHARACTER(LEN=:), ALLOCATABLE :: name 
        CHARACTER(LEN=:), ALLOCATABLE :: symbol 
        REAL*8 :: mass = 0.0
        INTEGER :: n_protons = 0
    END TYPE atomic_element

    CONTAINS

        TYPE(atomic_element) FUNCTION get_element(symbol_or_name) RESULT(elem)
            !< Factory for creating element types
            CHARACTER (len=*) :: symbol_or_name

            SELECT CASE(symbol_or_name)
            CASE("hydrogen", "protium", "hydrogen-1", "H")
                elem = atomic_element(name="hydrogen", symbol="H", mass=1.00794, n_protons=1)
            CASE("deuterium", "hydrogen-2", "2H", "D")
                elem = atomic_element(name="deuterium", symbol="D", mass=2.014101778, n_protons=1)
            CASE("tritium", "hydrogen-3", "3H", "T")
                elem = atomic_element(name="tritium", symbol="T", mass=3.0160492675, n_protons=1)
            CASE("helium", "He")
                elem = atomic_element(name="helium", symbol="He", mass=4.002602, n_protons=2)
            CASE("helium-3", "3He", "He-3")
                elem = atomic_element(name="helium", symbol="He", mass=3.0160293097, n_protons=2)
            CASE("lithium", "Li")
                elem = atomic_element(name="lithium", symbol="Li", mass=6.941, n_protons=3)
            CASE("beryllium", "Be")
                elem = atomic_element(name="beryllium", symbol="Be", mass=9.012182, n_protons=4)
            CASE("boron", "B")
                elem = atomic_element(name="boron", symbol="B", mass=10.811, n_protons=5)
            CASE("carbon", "C")
                elem = atomic_element(name="carbon", symbol="C", mass=12.0107, n_protons=6)
            CASE("nitrogen", "N")
                elem = atomic_element(name="nitrogen", symbol="N", mass=14.0067, n_protons=7)
            CASE("oxygen", "O")
                elem = atomic_element(name="oxygen", symbol="O", mass=15.9994, n_protons=8)
            CASE("fluorine", "F")
                elem = atomic_element(name="fluorine", symbol="F", mass=18.9984032, n_protons=9)
            CASE("neon", "Ne")
                elem = atomic_element(name="neon", symbol="Ne", mass=20.1797, n_protons=10)
            CASE("sodium", "Na")
                elem = atomic_element(name="sodium", symbol="Na", mass=22.98977, n_protons=11)
            CASE("magnesium", "Mg")
                elem = atomic_element(name="magnesium", symbol="Mg", mass=24.305, n_protons=12)
            CASE("aluminum", "Al")
                elem = atomic_element(name="aluminum", symbol="Al", mass=26.981538, n_protons=13)
            CASE("silicon", "Si")
                elem = atomic_element(name="silicon", symbol="Si", mass=28.0855, n_protons=14)
            CASE("phosphorus", "P")
                elem = atomic_element(name="phosphorus", symbol="P", mass=30.973761, n_protons=15)
            CASE("sulfur", "S")
                elem = atomic_element(name="sulfur", symbol="S", mass=32.065, n_protons=16)
            CASE("chlorine", "Cl")
                elem = atomic_element(name="chlorine", symbol="Cl", mass=35.453, n_protons=17)
            CASE("argon", "Ar")
                elem = atomic_element(name="argon", symbol="Ar", mass=39.948, n_protons=18)
            CASE("potassium", "K")
                elem = atomic_element(name="potassium", symbol="K", mass=39.0983, n_protons=19)
            CASE("calcium", "Ca")
                elem = atomic_element(name="calcium", symbol="Ca", mass=40.078, n_protons=20)
            CASE("scandium", "Sc")
                elem = atomic_element(name="scandium", symbol="Sc", mass=44.95591, n_protons=21)
            CASE("titanium", "Ti")
                elem = atomic_element(name="titanium", symbol="Ti", mass=47.867, n_protons=22)
            CASE("vanadium", "V")
                elem = atomic_element(name="vanadium", symbol="V", mass=50.9415, n_protons=23)
            CASE("chromium", "Cr")
                elem = atomic_element(name="chromium", symbol="Cr", mass=51.9961, n_protons=24)
            CASE("manganese", "Mn")
                elem = atomic_element(name="manganese", symbol="Mn", mass=54.938049, n_protons=25)
            CASE("iron", "Fe")
                elem = atomic_element(name="iron", symbol="Fe", mass=55.845, n_protons=26)
            CASE("cobalt", "Co")
                elem = atomic_element(name="cobalt", symbol="Co", mass=58.9332, n_protons=27)
            CASE("nickel", "Ni")
                elem = atomic_element(name="nickel", symbol="Ni", mass=58.6934, n_protons=28)
            CASE("copper", "Cu")
                elem = atomic_element(name="copper", symbol="Cu", mass=63.546, n_protons=29)
            CASE("zinc", "Zn")
                elem = atomic_element(name="zinc", symbol="Zn", mass=65.409, n_protons=30)
            CASE("gallium", "Ga")
                elem = atomic_element(name="gallium", symbol="Ga", mass=69.723, n_protons=31)
            CASE("germanium", "Ge")
                elem = atomic_element(name="germanium", symbol="Ge", mass=72.64, n_protons=32)
            CASE("arsenic", "As")
                elem = atomic_element(name="arsenic", symbol="As", mass=74.9216, n_protons=33)
            CASE("selenium", "Se")
                elem = atomic_element(name="selenium", symbol="Se", mass=78.96, n_protons=34)
            CASE("bromine", "Br")
                elem = atomic_element(name="bromine", symbol="Br", mass=79.904, n_protons=35)
            CASE("krypton", "Kr")
                elem = atomic_element(name="krypton", symbol="Kr", mass=83.798, n_protons=36)
            CASE("rubidium", "Rb")
                elem = atomic_element(name="rubidium", symbol="Rb", mass=85.4678, n_protons=37)
            CASE("strontium", "Sr")
                elem = atomic_element(name="strontium", symbol="Sr", mass=87.62, n_protons=38)
            CASE("yttrium", "Y")
                elem = atomic_element(name="yttrium", symbol="Y", mass=88.90585, n_protons=39)
            CASE("zirconium", "Zr")
                elem = atomic_element(name="zirconium", symbol="Zr", mass=91.224, n_protons=40)
            CASE("niobium", "Nb")
                elem = atomic_element(name="niobium", symbol="Nb", mass=92.90638, n_protons=41)
            CASE("molybdenum", "Mo")
                elem = atomic_element(name="molybdenum", symbol="Mo", mass=95.94, n_protons=42)
            CASE("technetium", "Tc")
                elem = atomic_element(name="technetium", symbol="Tc", mass=98, n_protons=43)
            CASE("ruthenium", "Ru")
                elem = atomic_element(name="ruthenium", symbol="Ru", mass=101.07, n_protons=44)
            CASE("rhodium", "Rh")
                elem = atomic_element(name="rhodium", symbol="Rh", mass=102.9055, n_protons=45)
            CASE("palladium", "Pd")
                elem = atomic_element(name="palladium", symbol="Pd", mass=106.42, n_protons=46)
            CASE("silver", "Ag")
                elem = atomic_element(name="silver", symbol="Ag", mass=107.8682, n_protons=47)
            CASE("cadmium", "Cd")
                elem = atomic_element(name="cadmium", symbol="Cd", mass=112.411, n_protons=48)
            CASE("indium", "In")
                elem = atomic_element(name="indium", symbol="In", mass=114.818, n_protons=49)
            CASE("tin", "Sn")
                elem = atomic_element(name="tin", symbol="Sn", mass=118.71, n_protons=50)
            CASE("antimony", "Sb")
                elem = atomic_element(name="antimony", symbol="Sb", mass=121.76, n_protons=51)
            CASE("tellurium", "Te")
                elem = atomic_element(name="tellurium", symbol="Te", mass=127.6, n_protons=52)
            CASE("iodine", "I")
                elem = atomic_element(name="iodine", symbol="I", mass=126.90447, n_protons=53)
            CASE("xenon", "Xe")
                elem = atomic_element(name="xenon", symbol="Xe", mass=131.293, n_protons=54)
            CASE("cesium", "Cs")
                elem = atomic_element(name="cesium", symbol="Cs", mass=132.90545, n_protons=55)
            CASE("barium", "Ba")
                elem = atomic_element(name="barium", symbol="Ba", mass=137.327, n_protons=56)
            CASE("lanthanum", "La")
                elem = atomic_element(name="lanthanum", symbol="La", mass=138.9055, n_protons=57)
            CASE("cerium", "Ce")
                elem = atomic_element(name="cerium", symbol="Ce", mass=140.116, n_protons=58)
            CASE("praseodymium", "Pr")
                elem = atomic_element(name="praseodymium", symbol="Pr", mass=140.90765, n_protons=59)
            CASE("neodymium", "Nd")
                elem = atomic_element(name="neodymium", symbol="Nd", mass=144.24, n_protons=60)
            CASE("promethium", "Pm")
                elem = atomic_element(name="promethium", symbol="Pm", mass=145, n_protons=61)
            CASE("samarium", "Sm")
                elem = atomic_element(name="samarium", symbol="Sm", mass=150.36, n_protons=62)
            CASE("europium", "Eu")
                elem = atomic_element(name="europium", symbol="Eu", mass=151.964, n_protons=63)
            CASE("gadolinium", "Gd")
                elem = atomic_element(name="gadolinium", symbol="Gd", mass=157.25, n_protons=64)
            CASE("terbium", "Tb")
                elem = atomic_element(name="terbium", symbol="Tb", mass=158.92534, n_protons=65)
            CASE("dysprosium", "Dy")
                elem = atomic_element(name="dysprosium", symbol="Dy", mass=162.5, n_protons=66)
            CASE("holmium", "Ho")
                elem = atomic_element(name="holmium", symbol="Ho", mass=164.93032, n_protons=67)
            CASE("erbium", "Er")
                elem = atomic_element(name="erbium", symbol="Er", mass=167.259, n_protons=68)
            CASE("thulium", "Tm")
                elem = atomic_element(name="thulium", symbol="Tm", mass=168.93421, n_protons=69)
            CASE("ytterbium", "Yb")
                elem = atomic_element(name="ytterbium", symbol="Yb", mass=173.04, n_protons=70)
            CASE("lutetium", "Lu")
                elem = atomic_element(name="lutetium", symbol="Lu", mass=174.967, n_protons=71)
            CASE("hafnium", "Hf")
                elem = atomic_element(name="hafnium", symbol="Hf", mass=178.49, n_protons=72)
            CASE("tantalum", "Ta")
                elem = atomic_element(name="tantalum", symbol="Ta", mass=180.9479, n_protons=73)
            CASE("tungsten", "W")
                elem = atomic_element(name="tungsten", symbol="W", mass=183.84, n_protons=74)
            CASE("rhenium", "Re")
                elem = atomic_element(name="rhenium", symbol="Re", mass=186.207, n_protons=75)
            CASE("osmium", "Os")
                elem = atomic_element(name="osmium", symbol="Os", mass=190.23, n_protons=76)
            CASE("iridium", "Ir")
                elem = atomic_element(name="iridium", symbol="Ir", mass=192.217, n_protons=77)
            CASE("platinum", "Pt")
                elem = atomic_element(name="platinum", symbol="Pt", mass=195.078, n_protons=78)
            CASE("gold", "Au")
                elem = atomic_element(name="gold", symbol="Au", mass=196.96655, n_protons=79)
            CASE("mercury", "Hg")
                elem = atomic_element(name="mercury", symbol="Hg", mass=200.59, n_protons=80)
            CASE("thallium", "Tl")
                elem = atomic_element(name="thallium", symbol="Tl", mass=204.3833, n_protons=81)
            CASE("lead", "Pb")
                elem = atomic_element(name="lead", symbol="Pb", mass=207.2, n_protons=82)
            CASE("bismuth", "Bi")
                elem = atomic_element(name="bismuth", symbol="Bi", mass=208.98038, n_protons=83)
            CASE("polonium", "Po")
                elem = atomic_element(name="polonium", symbol="Po", mass=209, n_protons=84)
            CASE("astatine", "At")
                elem = atomic_element(name="astatine", symbol="At", mass=210, n_protons=85)
            CASE("radon", "Rn")
                elem = atomic_element(name="radon", symbol="Rn", mass=222, n_protons=86)
            CASE("francium", "Fr")
                elem = atomic_element(name="francium", symbol="Fr", mass=223, n_protons=87)
            CASE("radium", "Ra")
                elem = atomic_element(name="radium", symbol="Ra", mass=226, n_protons=88)
            CASE("actinium", "Ac")
                elem = atomic_element(name="actinium", symbol="Ac", mass=227, n_protons=89)
            CASE("thorium", "Th")
                elem = atomic_element(name="thorium", symbol="Th", mass=232.0381, n_protons=90)
            CASE("protactinium", "Pa")
                elem = atomic_element(name="protactinium", symbol="Pa", mass=231.03588, n_protons=91)
            CASE("uranium", "U")
                elem = atomic_element(name="uranium", symbol="U", mass=238.02891, n_protons=92)
            CASE("neptunium", "Np")
                elem = atomic_element(name="neptunium", symbol="Np", mass=237, n_protons=93)
            CASE("plutonium", "Pu")
                elem = atomic_element(name="plutonium", symbol="Pu", mass=244, n_protons=94)
            CASE("americium", "Am")
                elem = atomic_element(name="americium", symbol="Am", mass=243, n_protons=95)
            CASE("curium", "Cm")
                elem = atomic_element(name="curium", symbol="Cm", mass=247, n_protons=96)
            CASE("belium", "Bk")
                elem = atomic_element(name="belium", symbol="Bk", mass=247, n_protons=97)
            CASE("californium", "Cf")
                elem = atomic_element(name="californium", symbol="Cf", mass=251, n_protons=98)
            CASE("einsteinium", "Es")
                elem = atomic_element(name="einsteinium", symbol="Es", mass=252, n_protons=99)
            CASE("fermium", "Fm")
                elem = atomic_element(name="fermium", symbol="Fm", mass=257, n_protons=100)
            CASE("mendelevium", "Md")
                elem = atomic_element(name="mendelevium", symbol="Md", mass=258, n_protons=101)
            CASE("nobelium", "No")
                elem = atomic_element(name="nobelium", symbol="No", mass=259, n_protons=102)
            CASE("lawrencium", "Lr")
                elem = atomic_element(name="lawrencium", symbol="Lr", mass=262, n_protons=103)
            CASE("rutherfordium", "Rf")
                elem = atomic_element(name="rutherfordium", symbol="Rf", mass=261, n_protons=104)
            CASE("dubnium", "Db")
                elem = atomic_element(name="dubnium", symbol="Db", mass=262, n_protons=105)
            CASE("seaborgium", "Sg")
                elem = atomic_element(name="seaborgium", symbol="Sg", mass=266, n_protons=106)
            CASE("bohrium", "Bh")
                elem = atomic_element(name="bohrium", symbol="Bh", mass=264, n_protons=107)
            CASE("hassium", "Hs")
                elem = atomic_element(name="hassium", symbol="Hs", mass=277, n_protons=108)
            CASE("meitnerium", "Mt")
                elem = atomic_element(name="meitnerium", symbol="Mt", mass=268, n_protons=109)
            CASE("darmstadtium", "Ds")
                elem = atomic_element(name="darmstadtium", symbol="Ds", mass=281, n_protons=110)
            CASE("roentgenium", "Rg")
                elem = atomic_element(name="roentgenium", symbol="Rg", mass=272, n_protons=111)
            CASE("copernicium", "Cn")
                elem = atomic_element(name="copernicium", symbol="Cn", mass=285, n_protons=112)
            CASE("nihonium", "Nh")
                elem = atomic_element(name="nihonium", symbol="Nh", mass=286, n_protons=113)
            CASE("flerovium", "Fl")
                elem = atomic_element(name="flerovium", symbol="Fl", mass=289, n_protons=114)
            CASE("moscovium", "Mc")
                elem = atomic_element(name="moscovium", symbol="Mc", mass=289, n_protons=115)
            CASE("livermorium", "Lv")
                elem = atomic_element(name="livermorium", symbol="Lv", mass=293, n_protons=116)
            CASE("tennessine", "Ts")
                elem = atomic_element(name="tennessine", symbol="Ts", mass=294, n_protons=117)
            CASE("oganesson", "Og")
                elem = atomic_element(name="oganesson", symbol="Og", mass=294, n_protons=118)
            CASE DEFAULT
                ERROR STOP "Unknown element or symbol"
            END SELECT

        END FUNCTION get_element 
    

END MODULE